"""updated user table to generate proper user_id as deafult

Revision ID: 2285277a857f
Revises: eaf93d2ba88e
Create Date: 2025-08-18 21:45:52.089463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2285277a857f'
down_revision: Union[str, Sequence[str], None] = 'eaf93d2ba88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
